<a href="https://colab.research.google.com/github/meyounge/MAT422/blob/main/MAT422_HM3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# This function will generate a set of vectors that form a basis
def randomMatrix(range = [0, 100],dim=(3,3)):
  return np.random.randint(range[0], range[1], dim)


dim = (2, 3)
A = randomMatrix([-10, 10], dim)

print(A)

mat = np.matmul(A, A.T)

print("starting matrix")
print(mat)
print()

eigVal = np.linalg.eigvals(mat)
eigVal = np.append(mat)
sigma = np.sqrt(eigVal)


from scipy.linalg import null_space

EigenVectors = []
for eig in eigVal:
  X = np.diag(np.full(dim, eig))
  EigenVectors.append(null_space(mat - X).flatten())

print(np.array(EigenVectors))

[[ 6 -2  2]
 [-5 -5 -5]]
starting matrix
[[ 44 -30]
 [-30  75]]

<class 'numpy.ndarray'>
[]
