<a href="https://colab.research.google.com/github/meyounge/MAT422/blob/main/MAT422_HM3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.4

##1.4.1 Singular value decomposition

In [89]:
import numpy as np
from scipy.linalg import null_space
# This function will generate a set of vectors that form a basis
def randomMatrix(range = [0, 100],dim=(3,3)):
  return np.random.randint(range[0], range[1], dim)

dim = (2,3)
A = randomMatrix([0, 10], dim)
print(A)

eigValU, eigVecU = np.linalg.eigh(np.matmul(A, A.T))

eigValU = np.append(eigValU, 0)
sigma = np.sqrt(eigValU)
mat = np.matmul(A.T, A)

from scipy.linalg import null_space

EigenVectors = []
for eig in eigValU:
  X = np.diag(np.full(dim[1], eig))
  EigenVectors.append(null_space(mat - X).flatten())

V = np.array(EigenVectors)
SIGMA = np.diag(sigma)
SIGMA = SIGMA[:-1]
U = eigVecU

print(SIGMA)
print(V)
print(U)

print()
print(np.round(np.matmul(np.matmul(U, SIGMA), V), 3))

[[2 3 7]
 [9 5 3]]
[[ 5.32429422  0.          0.        ]
 [ 0.         12.19228818  0.        ]]
[[ 0.57521727  0.01847694 -0.81779196]
 [ 0.71323729  0.47818112  0.51247965]
 [ 0.40052173 -0.87806687  0.26187959]]
[[-0.84869058  0.52888968]
 [ 0.52888968  0.84869058]]

[[2. 3. 7.]
 [9. 5. 3.]]
